#!/usr/bin/env bash
set -Eeuo pipefail

CONFIG=${YWD_TNC_CONFIG:-/etc/ywd-mmdvm-tnc/config.toml}
LOGDIR=${YWD_PACKETLOG_DIR:-/var/log/ywd-packetlog}
TNC_SERVICE=ywd-mmdvm-tnc.service
LOGGER_SERVICE=ywd-packetlog.service

fail() {
  printf 'FAIL: %s\n' "$*" >&2
  exit 1
}

printf '%s\n' '============================================================'
printf '%s\n' ' YWD-MMDVM-TNC MONITOR EVENTS - PHYSICAL GATE'
printf '%s\n' ' XRouter / TCP KISS / real HAT / real RF'
printf '%s\n' '============================================================'
printf '\n'

[[ -r "$CONFIG" ]] || fail "cannot read $CONFIG"
systemctl is-active --quiet "$TNC_SERVICE" || fail "$TNC_SERVICE is not active"
systemctl is-active --quiet "$LOGGER_SERVICE" || fail "$LOGGER_SERVICE is not active"

readarray -t cfg < <(python3 - "$CONFIG" <<'PY'
import sys, tomllib
with open(sys.argv[1], 'rb') as f:
    c = tomllib.load(f)
r = c.get('radio', {})
k = c.get('kiss', {})
m = c.get('monitor', {})
print('1' if m.get('enabled') is True else '0')
print(str(m.get('listen', '')))
print(str(m.get('port', '')))
print('1' if r.get('tx_enabled') is True else '0')
print(str(k.get('listen', '')))
print(str(k.get('port', '')))
PY
)

[[ ${cfg[0]:-0} == 1 ]] || fail '[monitor] is not enabled'
[[ ${cfg[1]:-} == 127.0.0.1 ]] || fail "physical gate expects loopback monitor bind; got ${cfg[1]:-missing}"
[[ ${cfg[2]:-} == 8002 ]] || fail "physical gate expects monitor port 8002; got ${cfg[2]:-missing}"
[[ ${cfg[3]:-0} == 1 ]] || fail 'radio.tx_enabled must be true for the TX lifecycle gate'

python3 - <<'PY' || fail 'cannot connect to passive monitor endpoint 127.0.0.1:8002'
import socket
with socket.create_connection(('127.0.0.1', 8002), timeout=2.0):
    pass
PY

printf 'TNC_SERVICE=ACTIVE\n'
printf 'PACKETLOGGER_SERVICE=ACTIVE\n'
printf 'MONITOR_LISTENER=127.0.0.1:8002\n'
printf 'KISS_LISTENER=%s:%s\n' "${cfg[4]:-?}" "${cfg[5]:-?}"

if systemctl is-active --quiet xrouter.service 2>/dev/null; then
  printf 'XROUTER_SERVICE=ACTIVE\n'
else
  printf 'XROUTER_SERVICE=NOT_CONFIRMED_BY_SYSTEMD\n'
fi

printf '\nCurrent TCP/8001 connections:\n'
ss -tn 2>/dev/null | grep ':8001' || true

TODAY="$(date +%F)"
JSONL="$LOGDIR/$TODAY.jsonl"
HUMAN="$LOGDIR/$TODAY.log"
BASELINE=0
[[ -f "$JSONL" ]] && BASELINE=$(wc -l <"$JSONL")

printf '\nLOGGER_JSONL=%s\n' "$JSONL"
printf 'LOGGER_HUMAN=%s\n' "$HUMAN"
printf 'BASELINE_JSONL_LINES=%s\n' "$BASELINE"
printf '\n'
printf '%s\n' 'No RF transmission is generated by this gate.'
printf '%s\n' 'From the XRouter sysop console, make ONE normal direct AX.25 connection:'
printf '\n    C 1 !KJ6YWD-5\n\n'
printf '%s\n' 'Wait for YWDNOD to answer and reach its prompt, then disconnect cleanly.'
printf '%s\n' 'That exchange should provide both real TX lifecycle events and real RF RX.'
printf '\nPress ENTER after the connect/disconnect has completed: '
IFS= read -r _

[[ -f "$JSONL" ]] || fail "logger did not create $JSONL"

python3 - "$JSONL" "$BASELINE" <<'PY'
from __future__ import annotations

import json
from pathlib import Path
import sys

path = Path(sys.argv[1])
baseline = int(sys.argv[2])
lines = path.read_text(encoding='utf-8').splitlines()
new_lines = lines[baseline:]
if not new_lines:
    raise SystemExit('FAIL: no new monitor records were written after the operator test')

records = []
for line in new_lines:
    try:
        value = json.loads(line)
    except json.JSONDecodeError as exc:
        raise SystemExit(f'FAIL: invalid JSONL monitor record: {exc}') from exc
    if isinstance(value, dict) and value.get('schema') == 1:
        records.append(value)

if not records:
    raise SystemExit('FAIL: no schema-1 monitor records were found')

rx = [r for r in records if r.get('event') == 'rx.frame']
if not rx:
    raise SystemExit('FAIL: no real rx.frame event was recorded')

by_request: dict[int, list[dict]] = {}
for record in records:
    request_id = record.get('request_id')
    if isinstance(request_id, int):
        by_request.setdefault(request_id, []).append(record)

required = ['tx.queued', 'tx.channel_clear', 'tx.dispatched', 'tx.complete']
qualified = None
for request_id, group in sorted(by_request.items()):
    kinds = [str(r.get('event')) for r in group]
    try:
        positions = [kinds.index(name) for name in required]
    except ValueError:
        continue
    if positions != sorted(positions) or len(set(positions)) != len(positions):
        continue
    if any(r.get('event') == 'tx.failed' for r in group):
        continue
    queued = next(r for r in group if r.get('event') == 'tx.queued')
    frame_hex = queued.get('frame_hex')
    queued_seq = queued.get('seq')
    submitted = [
        r for r in records
        if r.get('event') == 'tx.submitted'
        and r.get('frame_hex') == frame_hex
        and isinstance(r.get('seq'), int)
        and isinstance(queued_seq, int)
        and r['seq'] < queued_seq
    ]
    if not submitted:
        continue
    qualified = (request_id, group, submitted[-1])
    break

if qualified is None:
    observed = ','.join(str(r.get('event')) for r in records)
    raise SystemExit(
        'FAIL: no request had submitted -> queued -> channel_clear -> dispatched -> complete '
        f'in order; observed={observed}'
    )

request_id, group, submitted = qualified
selected = [submitted]
for name in required:
    selected.append(next(r for r in group if r.get('event') == name))

seqs = [r.get('seq') for r in selected]
if not all(isinstance(value, int) for value in seqs) or seqs != sorted(seqs):
    raise SystemExit(f'FAIL: successful TX event sequence numbers are not ordered: {seqs}')

clear = selected[2]
dispatched = selected[3]
if not isinstance(clear.get('raw_rssi'), int):
    raise SystemExit('FAIL: tx.channel_clear lacks raw_rssi')
if not isinstance(dispatched.get('selector_count'), int) or dispatched['selector_count'] <= 0:
    raise SystemExit('FAIL: tx.dispatched lacks a positive selector_count')

print(f'NEW_SCHEMA1_EVENTS={len(records)}')
print(f'REAL_RX_EVENTS={len(rx)}')
print(f'QUALIFIED_TX_REQUEST_ID={request_id}')
print('QUALIFIED_TX_EVENT_ORDER=' + '>'.join(str(r['event']) for r in selected))
print(f'QUALIFIED_TX_CHANNEL_CLEAR_RSSI={clear["raw_rssi"]}')
print(f'QUALIFIED_TX_SELECTOR_COUNT={dispatched["selector_count"]}')
print('MONITOR_EVENTS_PHYSICAL_GATE=PASS')
print('LOGGER_JSONL_VALID=PASS')
print('TX_AUTOMATIC_RETRY_ADDED=NO')
PY

printf '\nRecent human-readable packet log:\n'
tail -n 30 "$HUMAN" 2>/dev/null || true
