#!/usr/bin/env bash
set -Eeuo pipefail

CONFIG=${YWD_WEBUI_CONFIG:-/etc/ywd-mmdvm-tnc/webui.toml}
WAIT_SECONDS=${YWD_WEBUI_WAIT_SECONDS:-90}

if [[ ${EUID:-$(id -u)} -ne 0 ]]; then
  echo "Run as root: sudo bash $0" >&2
  exit 1
fi

[[ -f "$CONFIG" ]] || { echo "WEBUI_PHYSICAL_GATE=FAIL missing $CONFIG" >&2; exit 2; }
systemctl is-active --quiet ywd-mmdvm-tnc.service || { echo "WEBUI_PHYSICAL_GATE=FAIL ywd-mmdvm-tnc.service not active" >&2; exit 3; }
systemctl is-active --quiet ywd-webui.service || { echo "WEBUI_PHYSICAL_GATE=FAIL ywd-webui.service not active" >&2; exit 4; }

echo "============================================================"
echo " YWD-MMDVM-TNC WEBUI PHYSICAL OBSERVATION GATE"
echo "============================================================"
echo "No KISS frame or RF transmission is generated by this gate."
echo "It checks only the already-running read-only WebUI and waits"
echo "for normal packet/network activity to produce one live event."
echo

PYTHONPATH=/opt/ywd-mmdvm-tnc/source/src \
python3 - "$CONFIG" "$WAIT_SECONDS" <<'PY'
from __future__ import annotations
import http.client
import json
import sys
import time
from ywdweb.config import load_config

cfg = load_config(sys.argv[1])
wait = float(sys.argv[2])
host = "127.0.0.1" if cfg.web.listen == "0.0.0.0" else cfg.web.listen
port = cfg.web.port

conn = http.client.HTTPConnection(host, port, timeout=5)
conn.request("GET", "/api/v1/status")
resp = conn.getresponse()
assert resp.status == 200, resp.status
status = json.loads(resp.read())
assert status.get("read_only") is True
assert status.get("schema") == 1
print("WEBUI_STATUS_READ_ONLY=PASS")
print(f"WEBUI_MONITOR_STATE={status.get('monitor_state')}")
conn.close()

conn = http.client.HTTPConnection(host, port, timeout=5)
conn.request("POST", "/api/v1/status", body=b"x")
resp = conn.getresponse()
assert resp.status == 501, resp.status
resp.read()
conn.close()
print("WEBUI_HTTP_MUTATION_API=ABSENT")

conn = http.client.HTTPConnection(host, port, timeout=max(5, int(wait) + 5))
conn.request("GET", "/api/v1/stream")
resp = conn.getresponse()
assert resp.status == 200
print("WEBUI_SSE_CONNECTED=PASS")
deadline = time.monotonic() + wait
seen = None
while time.monotonic() < deadline:
    line = resp.fp.readline().decode("utf-8", "replace").strip()
    if line.startswith("data: "):
        candidate = json.loads(line[6:])
        if candidate.get("schema") == 1:
            seen = candidate
            break
if seen is None:
    raise SystemExit("WEBUI_PHYSICAL_GATE=FAIL no live schema-1 SSE event observed")
print(f"WEBUI_LIVE_EVENT={seen.get('event')}")
print(f"WEBUI_LIVE_SEQ={seen.get('seq')}")
print(f"WEBUI_LIVE_GENERATION={seen.get('_web_generation')}")
conn.close()
print("WEBUI_LIVE_SCHEMA1_SSE=PASS")
PY

echo "WEBUI_PHYSICAL_GATE=PASS"
echo "RF_GENERATED_BY_GATE=NO"
echo "KISS_FRAME_GENERATED_BY_GATE=NO"
echo "QUALIFIED_MODEM_PATH_CONTROLLED_BY_WEBUI=NO"
echo
echo "Open the configured WebUI from a trusted browser and verify:"
echo "  - live rows animate without excessive CPU/browser lag"
echo "  - RX/TX colors and lifecycle stages are readable"
echo "  - frame inspector/raw JSON/hex render correctly"
echo "  - history/stats/console populate when ywd-packetlog data exists"
echo "  - pausing the display does not stop monitor ingestion"
